- name: Ensure SSH directory exists
  file:
    path: /home/ubuntu/.ssh
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0700'

- name: Install Jenkins public key
  copy:
    src: /var/lib/jenkins/.ssh/ubuntu.pub
    dest: /home/ubuntu/.ssh/authorized_keys
    owner: ubuntu
    group: ubuntu
    mode: '0600'

- name: Install Redis
  apt:
    name: redis-server
    state: present
    update_cache: yes

- name: Listen on all interfaces
  lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^bind '
    line: 'bind 0.0.0.0'

- name: Disable protected mode
  lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^protected-mode'
    line: 'protected-mode no'

- name: Get master IP
  when: "'replica' in group_names"
  command: terraform -chdir=../../terraform output -raw redis_master_private_ip
  register: master_ip

- name: Configure replica
  when: "'replica' in group_names"
  lineinfile:
    path: /etc/redis/redis.conf
    line: "replicaof {{ master_ip.stdout }} 6379"

- name: Restart Redis
  service:
    name: redis-server
    state: restarted
    enabled: yes
