---

- name: Install Redis (correct package)
  apt:
    name: redis
    state: present
    update_cache: yes

- name: Allow redis to listen on all interfaces
  lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^bind'
    line: 'bind 0.0.0.0'

- name: Disable protected-mode
  lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^protected-mode'
    line: 'protected-mode no'

# MASTER ONLY
- name: Ensure Redis running
  when: "'master' in group_names"
  service:
    name: redis-server
    state: restarted
    enabled: yes

# REPLICA ONLY
- name: Configure replicaof
  when: "'replica' in group_names"
  lineinfile:
    path: /etc/redis/redis.conf
    line: "replicaof {{ hostvars[groups['tag_Role__master'][0]].ansible_host }} 6379"

- name: Restart Redis
  service:
    name: redis-server
    state: restarted
    enabled: yes
