---
- name: Install Redis
  apt:
    name: redis-server
    state: present
    update_cache: yes

- name: Allow redis to listen on all interfaces
  lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^bind'
    line: 'bind 0.0.0.0'

- name: Disable protected-mode
  lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^protected-mode'
    line: 'protected-mode no'

- name: Fetch master private IP (for replica only)
  when: "'replica' in group_names"
  command: terraform -chdir=../../terraform output -raw redis_master_private_ip
  register: master_ip_cmd

- name: Configure replicaof
  when: "'replica' in group_names"
  lineinfile:
    path: /etc/redis/redis.conf
    line: "replicaof {{ master_ip_cmd.stdout }} 6379"

- name: Restart Redis
  service:
    name: redis-server
    state: restarted
    enabled: yes
