plugin: amazon.aws.aws_ec2
regions:
  - us-east-1

filters:
  tag:Role: redis-server

hostnames:
  - public-ip-address

compose:
  ansible_host: public_ip_address

keyed_groups:
  - key: tags.Role
    prefix: tag_Role_
